on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        symfony: [6.x]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        include:
          - symfony: ^5.3
            php: 7.3
            dependency-version: prefer-lowest
          - symfony: ^5.3
            php: 7.3
            dependency-version: prefer-stable
          - symfony: ^5.3
            php: 7.4
            dependency-version: prefer-stable
          - symfony: ^5.3
            php: 8.1
            dependency-version: prefer-stable
          - symfony: ^7
            php: 8.2
            dependency-version: prefer-lowest
          - symfony: ^7
            php: 8.2
            dependency-version: prefer-stable
          - symfony: ^7
            php: 8.3
            dependency-version: prefer-stable

    name: PHP${{ matrix.php }} Symfony${{ matrix.symfony }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring

    - name: Install dependencies
      run: |
        composer require "symfony/http-foundation:${{ matrix.symfony }}" "symfony/http-kernel:${{ matrix.symfony }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest --with-all-dependencies

    - name: Execute Unit Tests
      run: vendor/bin/phpunit

    - name: Check PSR-12 Codestyle
      run: vendor/bin/phpcs --standard=psr12 --exclude=Generic.Files.LineLength src/
      if: matrix.os == 'ubuntu-latest'
